i+j
int i=6;
 int j=8;
 int k=i+j;
i
System.out.println("Good Morning")
greeting()
String mystr =greeting();
String greeting(String name){
    return "Good Morning"+name;
    
}
greeting("Hema")
String greeting(){
    return "Hello";
}
greeting()
int a=10, b=20;
int a=10, b=20;
int tem =a;
a=b;
b=tem;
System.out.println("After swapping: a=" +a+ ", b=" +b);
Boolean ispalindrome =new StringBuilder(str).reverse().toString().equals(str);
System.out.println("ispalindrome");
String str = "12321";
public int add(int a, int b){
    return a+b;
}
public int sub(int a, int b){
    return a-b;
}
public int mul(int a, int b){
    return a*b;
}
public int div(int a, int b){
    return a/b;
}
public int mod(int a, int b){
    return a%b;
}
add(10,30);
int c = sub(98,65);
div(9,2);
mul(56,2)
mod(65,3)
public boolean Palindrome(String str){
    String rev= new StringBuilder(str).reverse().toString();
    return str.equals(rev);}
Palindrome("ababa");
Palindrome("98756");
int addition(int a, int b){
    return(a+b);
}
addition(12,10)
int subtract (int a, int b){
    return a-b;
}
subtract(25,20)
 boolean palindrome(String a){
    String b= new StringBuilder(a).reverse().toString();
    return a .equals(b);
}
palindrome("abcedfg");
palindrome("56765");